-- MySQL Script generated by MySQL Workbench
-- Thu Aug 11 08:28:56 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema homeConomyAPI
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema homeConomyAPI
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `homeConomyAPI` DEFAULT CHARACTER SET utf8 ;
USE `homeConomyAPI` ;

-- -----------------------------------------------------
-- Table `homeConomyAPI`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `homeConomyAPI`.`role` (
                                                      `id` INT NOT NULL AUTO_INCREMENT,
                                                      `role` VARCHAR(255) NOT NULL,
    PRIMARY KEY (`id`),
    UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
    UNIQUE INDEX `role_UNIQUE` (`role` ASC) VISIBLE)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `homeConomyAPI`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `homeConomyAPI`.`user` (
                                                      `id` INT NOT NULL AUTO_INCREMENT,
                                                      `username` VARCHAR(45) NOT NULL,
    `email` VARCHAR(255) NOT NULL,
    `password` VARCHAR(255) NOT NULL,
    `role_id` INT NOT NULL,
    PRIMARY KEY (`id`),
    UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
    UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
    INDEX `fk_user_role1_idx` (`role_id` ASC) VISIBLE,
    CONSTRAINT `fk_user_role1`
    FOREIGN KEY (`role_id`)
    REFERENCES `homeConomyAPI`.`role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `homeConomyAPI`.`ownedCoins`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `homeConomyAPI`.`ownedCoins` (
    `id` VARCHAR(255) NOT NULL,
    `coin` VARCHAR(45) NOT NULL,
    `coinshortname` VARCHAR(255) NOT NULL,
    `amount` FLOAT NOT NULL,
    `user_id` INT NOT NULL,
    PRIMARY KEY (`id`),
    UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
    INDEX `fk_ownedCoins_user1_idx` (`user_id` ASC) VISIBLE,
    CONSTRAINT `fk_ownedCoins_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `homeConomyAPI`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `homeConomyAPI`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `homeConomyAPI`.`role` (
                                                      `id` INT NOT NULL AUTO_INCREMENT,
                                                      `role` VARCHAR(255) NOT NULL,
    PRIMARY KEY (`id`),
    UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
    UNIQUE INDEX `role_UNIQUE` (`role` ASC) VISIBLE)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `homeConomyAPI`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `homeConomyAPI`.`user` (
                                                      `id` INT NOT NULL AUTO_INCREMENT,
                                                      `username` VARCHAR(45) NOT NULL,
    `email` VARCHAR(255) NOT NULL,
    `password` VARCHAR(255) NOT NULL,
    `role_id` INT NOT NULL,
    PRIMARY KEY (`id`),
    UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
    UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
    INDEX `fk_user_role1_idx` (`role_id` ASC) VISIBLE,
    CONSTRAINT `fk_user_role1`
    FOREIGN KEY (`role_id`)
    REFERENCES `homeConomyAPI`.`role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `homeConomyAPI`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `homeConomyAPI`.`category` (
                                                          `id` INT NOT NULL AUTO_INCREMENT,
                                                          `category` VARCHAR(45) NOT NULL,
    PRIMARY KEY (`id`),
    UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
    UNIQUE INDEX `category_UNIQUE` (`category` ASC) VISIBLE)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `homeConomyAPI`.`expense`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `homeConomyAPI`.`expense` (
                                                         `id` INT NOT NULL AUTO_INCREMENT,
                                                         `price` FLOAT NOT NULL,
                                                         `date` DATE NOT NULL,
                                                         `title` VARCHAR(45) NOT NULL,
    `description` VARCHAR(255) NULL,
    `user_id` INT NOT NULL,
    `category_id` INT NOT NULL,
    PRIMARY KEY (`id`),
    UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
    INDEX `fk_expense_user1_idx` (`user_id` ASC) VISIBLE,
    INDEX `fk_expense_category1_idx` (`category_id` ASC) VISIBLE,
    CONSTRAINT `fk_expense_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `homeConomyAPI`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    CONSTRAINT `fk_expense_category1`
    FOREIGN KEY (`category_id`)
    REFERENCES `homeConomyAPI`.`category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
